//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/RsoLib")]
    public partial class Book : object
    {
        
        private string[] AuthorsField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private string TitleField;
        
        private string publishedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Authors
        {
            get
            {
                return this.AuthorsField;
            }
            set
            {
                this.AuthorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string publishedDate
        {
            get
            {
                return this.publishedDateField;
            }
            set
            {
                this.publishedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoSuchBookFault", Namespace="http://schemas.datacontract.org/2004/07/RsoLib")]
    public partial class NoSuchBookFault : object
    {
        
        private string OperationField;
        
        private string ProblemTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation
        {
            get
            {
                return this.OperationField;
            }
            set
            {
                this.OperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProblemType
        {
            get
            {
                return this.ProblemTypeField;
            }
            set
            {
                this.ProblemTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBooks", ReplyAction="http://tempuri.org/IService/GetBooksResponse")]
        ServiceReference1.GetBooksResponse GetBooks(ServiceReference1.GetBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBooks", ReplyAction="http://tempuri.org/IService/GetBooksResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetBooksResponse> GetBooksAsync(ServiceReference1.GetBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBookDetails", ReplyAction="http://tempuri.org/IService/GetBookDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.NoSuchBookFault), Action="http://tempuri.org/IService/GetBookDetailsNoSuchBookFaultFault", Name="NoSuchBookFault", Namespace="http://schemas.datacontract.org/2004/07/RsoLib")]
        ServiceReference1.GetBookDetailsResponse GetBookDetails(ServiceReference1.GetBookDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBookDetails", ReplyAction="http://tempuri.org/IService/GetBookDetailsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetBookDetailsResponse> GetBookDetailsAsync(ServiceReference1.GetBookDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBooksByYear", ReplyAction="http://tempuri.org/IService/GetBooksByYearResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.NoSuchBookFault), Action="http://tempuri.org/IService/GetBooksByYearNoSuchBookFaultFault", Name="NoSuchBookFault", Namespace="http://schemas.datacontract.org/2004/07/RsoLib")]
        ServiceReference1.GetBooksByYearResponse GetBooksByYear(ServiceReference1.GetBooksByYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBooksByYear", ReplyAction="http://tempuri.org/IService/GetBooksByYearResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetBooksByYearResponse> GetBooksByYearAsync(ServiceReference1.GetBooksByYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBooksByAuthor", ReplyAction="http://tempuri.org/IService/GetBooksByAuthorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.NoSuchBookFault), Action="http://tempuri.org/IService/GetBooksByAuthorNoSuchBookFaultFault", Name="NoSuchBookFault", Namespace="http://schemas.datacontract.org/2004/07/RsoLib")]
        ServiceReference1.GetBooksByAuthorResponse GetBooksByAuthor(ServiceReference1.GetBooksByAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBooksByAuthor", ReplyAction="http://tempuri.org/IService/GetBooksByAuthorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetBooksByAuthorResponse> GetBooksByAuthorAsync(ServiceReference1.GetBooksByAuthorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooks", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string query;
        
        public GetBooksRequest()
        {
        }
        
        public GetBooksRequest(string query)
        {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooksResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.Book[] GetBooksResult;
        
        public GetBooksResponse()
        {
        }
        
        public GetBooksResponse(ServiceReference1.Book[] GetBooksResult)
        {
            this.GetBooksResult = GetBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        public GetBookDetailsRequest()
        {
        }
        
        public GetBookDetailsRequest(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.Book GetBookDetailsResult;
        
        public GetBookDetailsResponse()
        {
        }
        
        public GetBookDetailsResponse(ServiceReference1.Book GetBookDetailsResult)
        {
            this.GetBookDetailsResult = GetBookDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooksByYear", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksByYearRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string year;
        
        public GetBooksByYearRequest()
        {
        }
        
        public GetBooksByYearRequest(string year)
        {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooksByYearResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksByYearResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.Book[] GetBooksByYearResult;
        
        public GetBooksByYearResponse()
        {
        }
        
        public GetBooksByYearResponse(ServiceReference1.Book[] GetBooksByYearResult)
        {
            this.GetBooksByYearResult = GetBooksByYearResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooksByAuthor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksByAuthorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string author;
        
        public GetBooksByAuthorRequest()
        {
        }
        
        public GetBooksByAuthorRequest(string author)
        {
            this.author = author;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooksByAuthorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksByAuthorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.Book[] GetBooksByAuthorResult;
        
        public GetBooksByAuthorResponse()
        {
        }
        
        public GetBooksByAuthorResponse(ServiceReference1.Book[] GetBooksByAuthorResult)
        {
            this.GetBooksByAuthorResult = GetBooksByAuthorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServiceChannel : ServiceReference1.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IService>, ServiceReference1.IService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.GetBooksResponse GetBooks(ServiceReference1.GetBooksRequest request)
        {
            return base.Channel.GetBooks(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBooksResponse> GetBooksAsync(ServiceReference1.GetBooksRequest request)
        {
            return base.Channel.GetBooksAsync(request);
        }
        
        public ServiceReference1.GetBookDetailsResponse GetBookDetails(ServiceReference1.GetBookDetailsRequest request)
        {
            return base.Channel.GetBookDetails(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBookDetailsResponse> GetBookDetailsAsync(ServiceReference1.GetBookDetailsRequest request)
        {
            return base.Channel.GetBookDetailsAsync(request);
        }
        
        public ServiceReference1.GetBooksByYearResponse GetBooksByYear(ServiceReference1.GetBooksByYearRequest request)
        {
            return base.Channel.GetBooksByYear(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBooksByYearResponse> GetBooksByYearAsync(ServiceReference1.GetBooksByYearRequest request)
        {
            return base.Channel.GetBooksByYearAsync(request);
        }
        
        public ServiceReference1.GetBooksByAuthorResponse GetBooksByAuthor(ServiceReference1.GetBooksByAuthorRequest request)
        {
            return base.Channel.GetBooksByAuthor(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBooksByAuthorResponse> GetBooksByAuthorAsync(ServiceReference1.GetBooksByAuthorRequest request)
        {
            return base.Channel.GetBooksByAuthorAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54185/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
